# CSCI 5454 Homework 3 FFT divide and conquer

09/20/2024
Jake Krol

In [5]:
import math
import numpy as np

In [6]:
def rou(n,k):
    # or just use math.e**((2j * math.pi * k)/ n)
    if k == 0:
        return 1
    real = round(np.cos((2 * math.pi * k) / n), 4)
    img = round(np.sin((2 * math.pi * k) / n), 4)
    z = complex(real, img)
    return z
def dft_matrix(a):
    n = len(a)
    M = np.zeros(shape=[n,n], dtype=complex)
    for k in range(n):
        for j in range(n):
            M[k,j] = rou(n, k*j)
    return M
def dft(a):
    M = dft_matrix(a)
    return M @ a
print(
    dft(np.array([0,1])),
    dft(np.array([0,0,1,1])),
    dft(np.array([0,0,0,0,1,1,1,1])),
    sep='\n'
)
    

[ 1.+0.j -1.+0.j]
[ 2.+0.j -1.-1.j  0.+0.j -1.+1.j]
[ 4.+0.j     -1.-2.4142j  0.+0.j     -1.-0.4142j  0.+0.j     -1.+0.4142j
  0.+0.j     -1.+2.4142j]


In [7]:
# p = 2, n = 8
dft(np.array([1, 0, 1, 0, 1, 0, 1, 0]))

array([4.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 4.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [8]:
# p = 3, n = 9
dft(np.array([1, 0, 0, 1, 0, 0, 1, 0, 0 ]))

array([3.+0.j, 0.+0.j, 0.+0.j, 3.+0.j, 0.+0.j, 0.+0.j, 3.+0.j, 0.+0.j,
       0.+0.j])

In [9]:
# a: n=15, p=5
dft(np.array([1, 0, 0, 0,0, 1, 0, 0, 0, 0,1,0,0,0, 0 ]))

array([3.+0.j, 0.+0.j, 0.+0.j, 3.+0.j, 0.+0.j, 0.+0.j, 3.+0.j, 0.+0.j,
       0.+0.j, 3.+0.j, 0.+0.j, 0.+0.j, 3.+0.j, 0.+0.j, 0.+0.j])

In [10]:
print(
    dft(np.array([1,0,1,0,1,0,1,0])),
    dft(np.array([1,0,0,1,0,0,1,0,0])),
    sep='\n'
)

[4.+0.j 0.+0.j 0.+0.j 0.+0.j 4.+0.j 0.+0.j 0.+0.j 0.+0.j]
[3.+0.j 0.+0.j 0.+0.j 3.+0.j 0.+0.j 0.+0.j 3.+0.j 0.+0.j 0.+0.j]


## Q3

### FFT 3-way divide and conquer

In [13]:
def fft_3(a,n):
    if n == 1:
        return a
    C = [a[i] for i in range(0, n-2, 3)]
    D = [a[i] for i in range(1, n-1, 3)]
    E = [a[i] for i in range(2, n, 3)]
    A_C = fft_3(C, n //3)
    A_D = fft_3(D, n//3)
    A_E = fft_3(E, n//3)
    A = np.repeat(np.nan, n).tolist()
    om1 = math.e**(2j * math.pi / 3)
    om2 = math.e**(2j * math.pi * 2 / 3)
    for l in range(0, n//3):
        om = math.e**(2j * math.pi * l / n)
        A[l] = A_C[l] + (om * A_D[l]) + ((om**2) * A_E[l])
        A[l+(n//3)] = A_C[l] + (om1 * om * A_D[l]) + (om1 * (om**2) * A_E[l])
        A[l+((2*n)//3)] = A_C[l] + (om2 * om * A_D[l]) + (om2 * (om**2) * A_E[l])
    return A
a = [3,1,1,3,1,1,3,1,1]
n = len(a)
fft_3(a,n)
    

[(15+0j),
 (-2.819077862357723+6.82374778540538j),
 (2.2981333293569315-3.869324526368755j),
 (6.000000000000002+5.196152422706632j),
 (-4.440892098500626e-16+1.9409616973091375j),
 (-2.2981333293569346-3.8693245263687523j),
 (5.9999999999999964-5.19615242270663j),
 (2.819077862357728+6.823747785405377j),
 (-5.551115123125783e-15-7.8498082153823825j)]