In [9]:
import math
import numpy as np


In [10]:
complex(0,2)
math.pi

3.141592653589793

In [29]:
def rou(n,k):
    #np.exp((complex(0,1) * math.pi * 2 * k) / n)
    if k == 0:
        return 1
    real = round(np.cos((2 * math.pi * k) / n), 4)
    img = round(np.sin((2 * math.pi * k) / n), 4)
    z = complex(real, img)
    return z

def dft_matrix(a):
    n = len(a)
    M = np.zeros(shape=[n,n], dtype=complex)
    for k in range(n):
        for j in range(n):
            M[k,j] = rou(n, k*j)
    return M

def dft(a):
    M = dft_matrix(a)
    return M @ a



    return M
print(
    dft(np.array([0,1])),
    dft(np.array([0,0,1,1])),
    dft(np.array([0,0,0,0,1,1,1,1])),
    sep='\n'
    )
#z = rou(4, 3)
#print(z.real, z.imag)
    

[ 1.+0.j -1.+0.j]
[ 2.+0.j -1.-1.j  0.+0.j -1.+1.j]
[ 4.+0.j     -1.-2.4142j  0.+0.j     -1.-0.4142j  0.+0.j     -1.+0.4142j
  0.+0.j     -1.+2.4142j]


In [30]:
# p = 2, n = 8
dft(np.array([1, 0, 1, 0, 1, 0, 1, 0]))

array([4.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 4.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [31]:
# p = 3, n = 9
dft(np.array([1, 0, 0, 1, 0, 0, 1, 0, 0 ]))

array([3.+0.j, 0.+0.j, 0.+0.j, 3.+0.j, 0.+0.j, 0.+0.j, 3.+0.j, 0.+0.j,
       0.+0.j])

In [63]:
# period of A seems equal to quotient
def dft_periodic(n, p):
    A = np.zeros(shape=[n])
    q = int(n / p)
    A[0] = q
    j = 1
    while j < (n/q):
        A[j*q] = q
        j += 1
    return A

dft_periodic(8,2)

array([4., 0., 0., 0., 4., 0., 0., 0.])

In [66]:
print(
    dft(np.array([1,0,1,0,1,0,1,0])),
    dft(np.array([1,0,0,1,0,0,1,0,0])),
    sep='\n'
)

[4.+0.j 0.+0.j 0.+0.j 0.+0.j 4.+0.j 0.+0.j 0.+0.j 0.+0.j]
[3.+0.j 0.+0.j 0.+0.j 3.+0.j 0.+0.j 0.+0.j 3.+0.j 0.+0.j 0.+0.j]


## Q3

### Q3a

In [95]:
def poly2trip(a):
    n = len(a)
    k = int(n / 3)
    print('k:',k)
    C = np.zeros([k])
    D,E = C,C
    j = 0
    print('a', a)
    while (j < k):
        C[j] = a[j*k]
        D[j] = a[(j*k)+1]
        E[j] = a[(j*k)+2]
        j +=1
    return C, D, E

poly2trip([1,0,1,0,1,0])

k: 2
a [1, 0, 1, 0, 1, 0]


(array([1., 1.]), array([1., 1.]), array([1., 1.]))